on:
  workflow_call:
    inputs:
      workingdirectory:
        required: true
        type: string

jobs:
  build-angular-app:
    name: Build Angular App
    runs-on: ubuntu-latest
    env:
      working-directory: '${{ github.workspace }}/${{ inputs.workingdirectory}}'
    steps:
      - uses: actions/checkout@v2

      - name: Navigating to working directory
        run: |
            echo "working directory: ${{ inputs.workingdirectory }}"
            cd ${{ inputs.workingdirectory }}
            ls -a
        
      - uses: actions/setup-node@v3.3.0
        name: Set up node.js
        with:
          node-version: 'latest'
          cache: 'npm'
          cache-dependency-path: ${{env.working-directory}}
        
      - name: Install angular
        working-directory: ${{env.working-directory}}
        run: npm install -g @angular/cli

      - name: Install dependencies
        working-directory: ${{env.working-directory}}
        run: |
          npm install

      - name: Build Angular App
        working-directory: ${{env.working-directory}}
        run: |
          ng build --configuration=production --output-path=pipelinebuild
        
      - name: Zip distribution
        working-directory: ${{env.working-directory}}
        run: |
          zip -r angularbuild.zip /pipelinebuild