on:
  workflow_call:
    inputs:
      workingdirectory:
        required: true
        type: string
      projectName:
        required: true
        type: string
      buildType:
        required: false
        default: "release"
        type: string

jobs:
  build-angular-app:
    name: Build Function App
    runs-on: ubuntu-latest
    env:
      working-directory: '${{ github.workspace }}/${{ inputs.workingdirectory}}'
      project-name: ${{inputs.projectName}}
      build-output-path: '${{ github.workspace }}/publish'
    steps:
      - uses: actions/checkout@v2

      - name: Navigating to working directory
        run: |
            echo "working directory: ${{ inputs.workingdirectory }}"
            cd ${{ inputs.workingdirectory }}
            ls -a
      
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: |
          dotnet restore ${{ env.working-directory }}/${{ env.project-name }}/${{ env.project-name }}.csproj
          dotnet restore ${{ env.working-directory }}/${{ env.project-name }}.Tests/${{ env.project-name }}.Tests.csproj
    
      - name: Build
        run: |
          dotnet build ${{env.working-directory}}/${{ env.project-name }}/${{ env.project-name }}.csproj --configuration ${{ inputs.buildType }} --no-restore
          dotnet build ${{ env.working-directory }}/${{ env.project-name }}.Tests/${{ env.project-name }}.Tests.csproj

      - name: Test
        run: dotnet test ${{env.working-directory}}/${{ env.project-name }}.Tests/${{ env.project-name }}.Tests.csproj --no-restore

      - name: Publish
        run: dotnet publish ${{env.working-directory}}/${{ env.project-name }}/${{ env.project-name }}.csproj --configuration ${{ inputs.buildType }} --no-restore --output ${{ env.build-output-path }}

      - name: Zip distribution
        working-directory: ${{env.working-directory}}
        run: |
          zip -r ${{ github.workspace }}/functionApp.zip ${{ env.build-output-path }}

      - name: Archive build
        uses: actions/upload-artifact@v3
        with:
          name: FunctionApp
          path: '${{ github.workspace }}/functionApp.zip'