on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
      swa-token:
        required: true
        type: string

jobs:
  build-angular-app:
    name: Build Function App
    runs-on: ubuntu-latest
    env:
      local-working-directory: ${{ github.workspace }}/Staging/AngularAppDirectory
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name}}
          path: ${{ env.local-working-directory }}

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ inputs.swa-token }}
          action: "upload"
          app_location: ${{ env.local-working-directory }}
          api_location: ""
          skip_app_build: true
          skip_api_build: true
          config_file_location: ${{ env.local-working-directory }}/assets