on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
      SWA-name:
        required: true
        type: string

jobs:
  build-angular-app:
    runs-on: ubuntu-latest
    env:
      local-working-directory: ${{ github.workspace }}/Staging/AngularAppDirectory
    outputs:
      swa-token: ${{ steps.fetchSWAToken.outputs.deploymenttoken }}
    steps:
      - name: Fetch SWA Token
        id: fetchSWAToken
        uses: azure/CLI@v1
        with: 
            inlineScript: |
                localdeploymentToken=$(az staticwebapp secrets list --name "${{ inputs.SWA-name }}" --query "properties.apiKey" -o tsv)
                echo "::add-mask::$localdeploymentToken"
                echo "deploymenttoken=$localdeploymentToken" >> "$GITHUB_OUTPUT"
                echo "Fetched token."

      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name}}
          path: ${{ env.local-working-directory }}

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{steps.fetchSWAToken.outputs.deploymenttoken}}
          action: "upload"
          app_location: ${{ env.local-working-directory }}
          api_location: ""
          skip_app_build: true
          skip_api_build: true
          config_file_location: ${{ env.local-working-directory }}/assets