name: Application deployment

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build-angular:
    uses: ./.github/workflows/buildAngularApp.jobs.yml
    with:
      workingdirectory: AngularApp
      artifactName: AngularApp

  build-functionapp:
    uses: ./.github/workflows/buildFunctionApp.jobs.yml
    with:
      workingdirectory: TGC.Site.API
      projectName: TGC.Site.API
      artifactName: TGC.Site.API

  deploy-test-infrastructure:
    needs: [build-angular,build-functionapp]
    name: Deploy infrastructure to Test
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: Deploy Test Infrastructure
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: '${{ secrets.AZURE_RG }}-TST'
        template: Bicep/main.bicep
        parameters: 'deploymentEnvironment=TST'
    
    - name: Fetch SWA Token
      id: fetchSWAToken
      uses: azure/CLI@v1
      with:
          inlineScript: |
              deploymentToken=$(az staticwebapp secrets list --name "asgerthyregoddk-tst-swa" --query "properties.apiKey" -o tsv)
              echo "::add-mask::$deploymentToken" 
              echo "somestate=$deploymentToken" >> "$GITHUB_ENV"
              echo "Fetched token."
    
    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: AngularApp
        path: ${{ github.workspace }}/Staging/AngularAppDirectory

    - name: Unzip AngularAppArtifact
      run: |
        cd ${{ github.workspace }}/Staging/AngularAppDirectory
        ls -a

    - name: Build And Deploy
      id: builddeploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ env.somestate }}
        # repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
        action: "upload"
        ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
        # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
        app_location: "${{ github.workspace }}/Staging/AngularAppDirectory" # App source code path
        api_location: "" # Api source code path - optional
        skip_app_build: true
        skip_api_build: true
        config_file_location: /assets
        #output_location: "" # Built app content directory - optional
        ###### End of Repository/Build Configurations ######

    # - name: Use the value
    #   id: step_two
    #   run: |
    #       echo "${{ env.somestate }}"

  deploy-prod-infrastructure:
    needs: deploy-test-infrastructure
    name: Deploy infrastructure to Prod
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy Prod Infrastructure
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: '${{ secrets.AZURE_RG }}-PRD'
        template: Bicep/main.bicep
        parameters: 'deploymentEnvironment=PRD'