name: Application deployment

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # - name: Create Test Resource Group
    #   uses: azure/CLI@v1
    #   with:
    #     inlineScript: |
    #       az group create --location westeurope --name asgerthyregoddk-tst

      # Deploy Bicep file
    - name: Deploy Test Infrastructure
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: '${{ secrets.AZURE_RG }}-TST'
        template: Bicep/main.bicep
        parameters: 'deploymentEnvironment=TST'
        failOnStdErr: false

    - name: Deploy Prod Infrastructure
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: '${{ secrets.AZURE_RG }}-PRD'
        template: Bicep/main.bicep
        parameters: 'deploymentEnvironment=PRD'
        failOnStdErr: false